package love.shop.domain.delivery;

public enum DeliveryStatus {
    PENDING_PAYMENT, LABEL_CREATED, PICKED_UP, IN_TRANSIT, ARRIVED_AT_FACILITY, DELIVERED, DELIVERY_EXCEPTION, RETURNING_TO_SENDER,
    CANCELLED
}
